services:
  - type: web
    name: srh-global-export
    env: bun
    rootDir: .
    buildCommand: cd . && bun install && bun run build:node
    startCommand: bun run serve
    envVars:
      - key: VITE_EMAILJS_SERVICE_ID
        value: service_dnq358a
      - key: VITE_EMAILJS_TEMPLATE_ID
        value: template_tplyqzl
      - key: VITE_EMAILJS_PUBLIC_KEY
        value: LUskdloaMEE1IxgeM
      - key: NODE_ENV
        value: production
