services:
  - type: static
    name: srh-global-export
    env: bun
    buildCommand: bun install && bun run build:static
    staticPublishPath: dist/client/client
    envVars:
      - key: VITE_EMAILJS_SERVICE_ID
        value: service_dnq358a
      - key: VITE_EMAILJS_TEMPLATE_ID
        value: template_tplyqzl
      - key: VITE_EMAILJS_PUBLIC_KEY
        value: LUskdloaMEE1IxgeM
      - key: NODE_ENV
        value: production
